only support x86_64-linux
eachDefaultSystem was giving error messages like:

$ nix flake show
git+file:///home/ryantm/p/nixpkgs-update?ref=update-nixpkgs-ghc&rev=a9c8aded8f9f47679113c786e8a10e7556a05848
├───defaultPackage
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ nix
error: --- Error --- nix-daemon
a 'aarch64-linux' with features {} is required to build '/nix/store/ni5699wkzqsjbw8zpbrdgfkig2hs7jhf-remove-references-to.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
(use '--show-trace' to show detailed location information)